### ISSUE TITLE
Ou est le code?

### ISSUE THREAD

**Issue by Pallandos** [GHITATT/projet_cpp#1]
Il n'y a rien

**Comment by GHITATT** [comment]
Bonjour monsieur Pallandos, 
Nous nous excusons du retard de notre réponse. Nos développeurs travaillent d'arrache pied pour essayer de vous livrer un produit satisfaisant, je vous pris donc d'excuser qu'ils n'aient pas voulu vous livrer un code vide et inutile. 
Une partie du produit sera livrée au plus tard demain soir. 
Je reste à votre disposition pour répondre à davantage de questions.
Bien à vous, 
Ghita, Developpeuse, maitaineuse de ce dépôt, et déesse céleste incontestable

**Comment by Pallandos** [comment]
Rien que ça? Très bien j'accepte vos excuses 

Bonne soirée 
Biz à la déesse
